'use strict';

window.INVENTORLAB_RETRIEVAL_PROMPTS = {
  ct2:{change:'The treasure moves to a different place. Without reusing your old route, explain how you would make the instructions precise enough for a new human robot.',lookFor:'A strong answer replaces vague words with exact actions, directions, counts or landmarks and adapts the algorithm to the new route.'},
  d1:{change:'Dash starts facing a different direction. What part of your sequence must you reconsider before pressing RUN?',lookFor:'The learner should reason about order and the changed starting state rather than simply adding commands.'},
  d2:{change:'The customer moves farther away and Dash now stops short. How would you use the size of the miss to decide the next change?',lookFor:'Measure the error, change one relevant value, keep the start condition fair, then retest.'},
  d3:{change:'The dance pattern changes from three moves to four. How would you decide what belongs inside the loop?',lookFor:'Identify the repeated unit first, then choose the repeat structure; one-time setup stays outside.'},
  d4:{change:'One corridor of the maze is moved but the rest is unchanged. What should you retest first?',lookFor:'Decompose the route, retest the affected section from a controlled start, then reintegrate.'},
  d5:{change:'The obstacle is moved closer to Dash. What should stay the same in the sensing rule, and what might need to change?',lookFor:'Separate sensor input from the program decision and adapt the threshold/response only if evidence requires it.'},
  w1:{change:'The mechanism moves in the wrong direction after you rebuild it. How would you decide whether the problem is motor direction or the physical linkage?',lookFor:'Test the motor/subsystem separately and inspect the mechanism before changing both code and build at once.'},
  w2:{change:'You swap one gear for a larger gear. Predict what measurement would tell you whether speed changed.',lookFor:'Use a fair time or rotation comparison and explain the relationship between gear size and movement.'},
  w3:{change:'The creature should react to a different sensor event. What parts of INPUT → DECISION → OUTPUT change?',lookFor:'The input/condition may change while the decision structure and output chain remain explicit.'},
  s1:{change:'The target sprite moves to another starting coordinate. What should you predict before testing the chase again?',lookFor:'Reason from event, coordinates and movement rather than memorising the original position.'},
  s2:{change:'The game is restarted after scoring 7 points. What must happen to the score state before play begins?',lookFor:'Reset/initialise the variable at the correct event so old state does not leak into the new game.'},
  m1:{change:'Instead of shaking the micro:bit, button A should trigger the output. What stays the same and what changes?',lookFor:'The event/input changes; the event-driven input → program → output model remains.'},
  m2:{change:'The dice should now generate values 1–10. What changes in the program, and what does not change about randomness?',lookFor:'Change the range while retaining event, variable and display logic; small samples still need not be evenly distributed.'},
  m3:{change:'A third micro:bit joins the system. What settings or message design must be checked before debugging the display?',lookFor:'Communication compatibility/group/addressing and message handling come before cosmetic output debugging.'},
  x1:{change:'The rescue attachment fails but navigation still works. What should you test next and why?',lookFor:'Isolate the rescue subsystem, reproduce the failure, then reintegrate after it works independently.'},
  e1:{change:'The detector works in a quiet room but alarms when a door slams. How would you investigate without simply making it less sensitive?',lookFor:'Measure/observe the noisy input, characterise false positives, test threshold/boundary behaviour and preserve detection reliability.'},
  e6:{change:'The sender reports “sent” but the receiver sometimes misses messages. What evidence would distinguish sending from successful delivery?',lookFor:'Use acknowledgement/message IDs/retries or another explicit receipt mechanism and measure successful exchanges.'},
  e7:{change:'Calibration improves the mean result but the spread becomes much larger. Is that automatically better?',lookFor:'No. Compare both systematic error and variability; calibration should be validated across repeated trials.'},
  e2:{change:'A faster delivery route succeeds only 6/10 times. How would you decide whether the optimisation is acceptable?',lookFor:'Use an explicit objective plus reliability constraint; speed alone is not sufficient.'},
  e8:{change:'A user attempts an impossible state transition. What should the simulator do, and how would you test it?',lookFor:'Reject/block or handle the invalid transition explicitly and include it as an edge-case test.'},
  e3:{change:'The app button says the robot is ON, but the robot never acknowledged the command. What state should the UI show?',lookFor:'UI state should reflect confirmed system state or uncertainty, not merely the command that was sent.'},
  e4:{change:'The same behaviour must now work with a different input value. What is the strongest sign the abstraction is genuine?',lookFor:'A clear function/parameter contract adapts without copying a near-identical block of code.'},
  e11:{change:'One reading strongly supports the hypothesis while the rest do not. What should happen before drawing a conclusion?',lookFor:'Inspect the full dataset, provenance and possible outlier causes; do not cherry-pick.'},
  e9:{change:'The LED does not light after a code change. How would you isolate whether wiring or software is responsible?',lookFor:'Use a minimal known-good hardware/software test and change one subsystem at a time.'},
  e5:{change:'The printed part is too tight. What evidence should you collect before editing the CAD dimensions?',lookFor:'Measure the actual print and target fit, identify error direction/magnitude, then make a justified single change.'},
  e10:{change:'The page looks polished to its author but a new user cannot find the evidence. What should be tested next?',lookFor:'Run an unaided usability task with a new user and measure whether the evidence and controls are discoverable.'},
  i1:{change:'One subsystem fails during the Smart Room demo. How should the system behave, and what does that reveal about the architecture?',lookFor:'Use fallback/manual override/diagnosability, isolate the failed subsystem and show that requirements include failure behaviour, not only normal success.'}
};

window.INVENTORLAB_ENGINEER_RETRIEVAL_CHECKS = {
  e1:{q:'Repeated harmless movement triggers the alarm. What should you investigate first?',opts:['Raw sensor behaviour and threshold/false-positive evidence','Add more outputs','Assume the sensor is unusable'],ans:0,explain:'A reliability problem should be characterised from the input and boundary evidence before changing the whole design.'},
  e6:{q:'Why is “message sent” not proof of delivery?',opts:['The receiver may never receive or process it','Radio messages always duplicate','Only the screen can confirm delivery'],ans:0,explain:'Reliable protocols distinguish attempted transmission from acknowledged receipt/processing.'},
  e7:{q:'Mean error improves but trial spread doubles. Best conclusion?',opts:['Calibration needs further validation because consistency worsened','Calibration is automatically successful','Ignore variation if the mean is close'],ans:0,explain:'Accuracy and repeatability are different evidence dimensions.'},
  e2:{q:'A route is fastest but succeeds only 60% of the time. What is missing?',opts:['A reliability constraint in the optimisation objective','More decorative blocks','A second robot'],ans:0,explain:'Optimisation is meaningful only relative to an objective and constraints.'},
  e8:{q:'What is a strong state-model test?',opts:['Attempt a transition that should be illegal and verify it is blocked/handled','Only test the happy path','Rename the states'],ans:0,explain:'Invalid transitions reveal whether the model actually constrains system behaviour.'},
  e3:{q:'The app sent ON but no acknowledgement arrived. What is safest?',opts:['Show pending/unknown until state is confirmed','Show ON immediately as fact','Hide all status'],ans:0,explain:'Interface state should not claim certainty the system has not established.'},
  e4:{q:'What most strongly supports genuine abstraction?',opts:['One parameterised function handles related inputs without copied code','The program is longer','Every value is hard-coded'],ans:0,explain:'A reusable contract separates the general behaviour from changing values.'},
  e11:{q:'An outlier supports your preferred conclusion. What should you do?',opts:['Investigate its provenance before deciding whether it belongs','Keep only the outlier','Delete it automatically'],ans:0,explain:'Outliers can be errors or important real behaviour; provenance comes first.'},
  e9:{q:'LED output fails. Best fault-isolation move?',opts:['Test a minimal known-good circuit and minimal known-good code separately','Rewire and rewrite everything together','Increase voltage randomly'],ans:0,explain:'Subsystem isolation preserves causal evidence and is safer.'},
  e5:{q:'A printed part is too tight. Strongest next step?',opts:['Measure actual dimensions and compare with the target before editing CAD','Scale it randomly','Print the same file repeatedly'],ans:0,explain:'Iteration should respond to measured error.'},
  e10:{q:'Who is most useful for testing whether a mission website is understandable?',opts:['A new user completing a defined task unaided','Only the author','Someone who already memorised the interface'],ans:0,explain:'Fresh-user usability testing reveals discoverability and explanation gaps.'},
  i1:{q:'A subsystem fails during integration. Best architectural response?',opts:['Contain/isolate the failure and use defined fallback behaviour','Pretend the demo is complete','Restart until it happens to work'],ans:0,explain:'Systems engineering includes failure behaviour, diagnosability and graceful degradation.'}
};
